* but is this music?
https://youtu.be/46w99bZ3W_M?t=112

* https://www.youtube.com/watch?v=q5yxIzs5Wug
** mataphor
> like the wind turbine converts the wind to the electricity
- like the velocity changes into pressure?
- like the ...
** D minor https://youtu.be/q5yxIzs5Wug?t=170
> it sadness!
what? carry with other sound?
> in lanuage, we use template? https://youtu.be/q5yxIzs5Wug?t=277
cool words.
> reaching for the nears possible words and ajust our thoughs
yeah, songs much harder than lanugage
> Toms Wait said it was like capture birds withou killing them.
pretty accurate
> Solo and surrounded by machinese, I can kinda of free
cool.
** this is so cool
abstraction upon abstraction without feeling strange.

Each layer is repeated in some how at different domain.

What's the mathematical domain is this?

I don't think we have...

I already lost int the layer, but the creator can.

Even 14:30, she can still add thing using her theory into this magic
thing.

* drum

** the blue ball is so funny: https://youtu.be/SmE7A12RHQs?t=85
* theory
拨动长度 L 的琴弦，我们听到的是基因和泛音的混合， 它们之间是 1: 2 的关系

any relation to this: https://github.com/randomwangran/computing/blob/master/classic/continuum/heat.org ?

* \pi 之歌

** 左手在弹什么？
https://youtu.be/wM-x3pUcdeo?t=11
** 右手的 \pi 为什么会有两指，对于某一个音符？
** 谱子
https://www.sheetmusicplus.com/title/song-from-digital-sheet-music/20044129?ac=1
